# Generated by Django 3.1.1 on 2020-09-15 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suid', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=students.models.student_upload_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
