# Generated by Django 3.1.1 on 2020-09-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
